### ISSUE TITLE
Customizable NaN Color

### ISSUE THREAD

**Issue by low-sky** [Astroua/CARTAvis#103]
Users have commented that they would like the NaN color to not be bright red.  I propose that the default NaN color be the bottom of whatever color table is in use at the time.  Users should have a tab option on `Colormap` settings below `Color Map` and `Transform` labeled `NaN Color` with a color picker and a checkbox that just says `Bottom of Color Table`

**Comment by durga2112** [comment]
@pfederl: would [this](https://github.com/Astroua/CARTAvis/blob/1efe006814c92287795b36c1fc9b3d16e21575fa/carta/cpp/core/ImageRenderService.cpp#L68) be where the NaN colour is currently being set?

**Comment by pfederl** [comment]
Correct.

**Comment by slovelan** [comment]
This should be in my next check-in.
