### ISSUE TITLE
Only one channel being loaded for some data cubes

### ISSUE THREAD

**Issue by durga2112** [Astroua/CARTAvis#123]
Some of my data cubes are showing up as single channel images when they are loaded. One of these cubes is N15693D.fits from the CARTAImages repository.

This is happening in both the latest develop code and the latest OS X binary.

**Comment by slovelan** [comment]
I guess I am curious as to why you think N15693D.fits is not 
2-dimensional.  When I load
my local copy of it,  there is a report that it has an empty or 
nonexistent spectral axis. The
shape is reported to be [170,182].  Are you seeing something different?

**Comment by durga2112** [comment]
Try loading it in ds9 or another viewer. In ds9, it shows up as an 18-channel data cube. It used to load like this in CARTA as well, but sometime within the last couple of months (I added it to the CubesTest folder in the images repository in October, but I hadn't looked at it since then until this past week) it started loading as a 2D image.

Actually, now that I look more closely, the shape is being reported as [60, 60, 18] in CARTA, but there is no channel animator for it.

**Comment by slovelan** [comment]
We must be looking at a different image then.  ds9 seemed to agree with 
CARTA.  Can you send me the
URL where the image is located?
Susan

**Comment by durga2112** [comment]
If you go to the [CARTAImages repository](https://docs.google.com/a/ualberta.ca/folderview?id=0B71tg6U4W78KY3dXZ1JlYnlCSU0&usp=drive_web), you should be able to find it in the CubesTest directory.

**Comment by slovelan** [comment]
Just found it, and now I can see the problem.  Apparently there is more 
than one version of
N15693D.fits floating around.
Susan

**Comment by slovelan** [comment]
The particular image cited in this issue has a LINEAR axis rather than a 
SPECTRAL axis.
I could not see any support for LINEAR axes in our code so I added it to 
Carta/Lib/AxisInfo,
the CoordinateFormatter and other associated classes.  This allows the 
cube to be displayed.
The checked in code is in the susan branch.
