### ISSUE TITLE
v0.5.0 issues for hotfix

### ISSUE THREAD

**Issue by low-sky** [Astroua/CARTAvis#135]
There are a two issues with v0.5.0 as seen on Mac.  Some appear to be with the histogram.  
- [ ] Images in the SmallMultiples test suite produce a crash when opened: [cubelog.txt](https://github.com/Astroua/CARTAvis/files/123099/cubelog.txt)  This issue goes away when the histogram plugin is closed.  If open the plugin again and then make the link, it crashed immediately upon linking.
- [ ] If I create an image stack by loading three images from the SmallMultiples test data with the histogram viewer closed so it doesn't crash, I can trigger something that runs the processor up to 100% and hangs.  To reproduce
  1. Load three images from the SmallMultiples directory
  2. Open the Image Settings > Stack Menu, 
  3. Unselect Auto Select
  4. Click one image, Select `Plus` compositing.
  5. Click another image ... hang.
The current code may fix these.

**Comment by slovelan** [comment]
I have not been able to reproduce the SmallMultiples test suite crash with the current code base.  I did not test all of the SmallMultples images, but I did test the first 3 with the histogram plugin open and did not experience a crash.  Unless there is something I am missing when I try to reproduce it, it appears fixed.

**Comment by slovelan** [comment]
I have also not been able to reproduce the second issue, the hang, with my local code base.

**Comment by slovelan** [comment]
By accident, I stumbled on a reproduce of the second issue, and a fix should be in with my most recent commit.
