### ISSUE TITLE
v0.5.0 Enhancement requests

### ISSUE THREAD

**Issue by low-sky** [Astroua/CARTAvis#136]
Here are a few feature requests.

- [x] Selecting Image Settings > Grid  and unselecting the Grid Lines check box should keep the axes drawn.  The Axes/Border should toggle grid lines on/off (as it does).
- [x] In the Contour selection, being able to type a number in the `Level Count` box would be nice (as opposed to using the buttons).
- [x] Percentile based contours aren't functional.
- [x] Logarithmically spaced contours couldn't be generated.
- [x] Is it possible to toggle into the `Contour` set parameters and have them start with all the levels selected.  The basic action will be to change the properties of all the contours.
- [x] Related to the above, when I try to change the thickness of the contour, I get "Could not set thickness; contour levels were invalid: 15 (where the 15 is the contour level).  
- [x] The most common application for an image stack compositing will be to make an RGB triplet from three sets of data.  In our framework, this is using the Plus Composer and assigning one image to R, one to G, and one to B.  Can we enhance the GUI to make this easier?  One thought I had was to just put a button in the space where it says `Auto Select` and `Pan/Zoom All` that says `RGB composite` which:
  *  Sets the color map for all images in the stack to Grey
  *  Sets the Composer to Plus for all images in the stack
  *  Sets the first image to Red, second to Green, third to Blue and then turns the Transparency to 0 for the other images in the stack.  Then a user can reassign the colours by navigating through the stack and clicking what channel they want to display.
- [x] Setting an image to a specific colour channel (e.g., the Red) could change the image name in the stack to be that colour.

**Comment by slovelan** [comment]
These should be fixed with the exception of "The most common application....".  That one will need to wait until the complete over haul of stack functionality discussed at the most recent Socorro Carta meetings.
