### ISSUE TITLE
carta.sh doesn't look at a new filename

### ISSUE THREAD

**Issue by teuben** [Astroua/CARTAvis#147]
very simple fix:   move the imagefile=$HOME/CARTA/Images/aJ.fits 
as a default line before the cmdline parser while[]

**Comment by astrilet** [comment]
it is actually a build problem, as I was testing it during build process I move the line after while loop... :(
In the original script that is checked in into our repository it is before cmdline parser while. 
(see carta.sh script in carta/scripts directory)
In the next release build I will be more careful. 
Alex
