### ISSUE TITLE
Clip Value must be in [0,1)

### ISSUE THREAD

**Issue by low-sky** [Astroua/CARTAvis#152]
When clicking on the 100% Clipping button in v0.6.0, the UI displays a warning message "Clip Value must be in [0,1)" and the colour map does not update.  The attached figure shows one instance of this bug.

![clipbug](https://cloud.githubusercontent.com/assets/1139910/14835570/9c0a4450-0bc7-11e6-9042-a0158f928997.png)

**Comment by slovelan** [comment]
This should be fixed in my next check-in.

**Comment by low-sky** [comment]
Resolved.
