### ISSUE TITLE
Gamma value enhancements

### ISSUE THREAD

**Issue by low-sky** [Astroua/CARTAvis#153]
Users commented that the Gamma value in the `Colormap` view -> `Transform` window session, should accept text entry to set the value.  The 2D Gamma window was deemed to be confusing.  This should be remedied by turning the grid lines into curves indicating the relative spacing between values (i.e. tighter at the top and spreading apart, like an [Atari Logo](https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Atari_Official_2012_Logo.svg/2000px-Atari_Official_2012_Logo.svg.png).  Failing that, this should just be a text entry box (i.e., remove the grab-and-drag UI element).

**Comment by teuben** [comment]
I likened it to the GUI for this in Darktable, they have exactly these
spreading lines, and I find it very intuitive (with those lines).
Before the lines were there I didn't even realize what was going on, or
never made the connection to Darktable.

**Comment by slovelan** [comment]
This should be addressed at my next check-in.

**Comment by low-sky** [comment]
Looking good.
