### ISSUE TITLE
Tape Deck clicking

### ISSUE THREAD

**Issue by low-sky** [Astroua/CARTAvis#154]
Clicking at a position in the Tape Deck should go to that channel in the cube.  Thus, if I click in the tape deck 75% of the way along, it should go to the channel that is 3/4ths of the way along in the cube.  

Currently, the functionality jumps in that direction but does not go to that channel.

**Comment by slovelan** [comment]
This should be fixed with my next check-in.

**Comment by low-sky** [comment]
Behaving properly.
