### ISSUE TITLE
Colorbar limits

### ISSUE THREAD

**Issue by low-sky** [Astroua/CARTAvis#155]
Users suggested being able to set the limits of the color table by text entry in the color bar bounds.  This would be particularly useful when the histogram is not displayed.  The sample figure below shows the case with units, which was requested.  Thus, I could have a map in Jy/pixel and type in a brightness cut in Kelvins and get the right values set for the color map.

![colormap](https://cloud.githubusercontent.com/assets/1139910/14835890/9425dc34-0bc9-11e6-836b-c2f6cf2b7b72.png)

**Comment by slovelan** [comment]
This should be addressed with the next check-in.

**Comment by low-sky** [comment]
Working
