### ISSUE TITLE
Grid lines change angles on zoom

### ISSUE THREAD

**Issue by low-sky** [Astroua/CARTAvis#183]
The grid lines should intersect at 90° angles when considering angles << 1 radian.  The current code appears to pick the number of grid lines to draw and ignore the angle between the latitude and longitude.

https://youtu.be/M1EpJ61F0fw

**Comment by slovelan** [comment]
This should be fixed with my next check-in.

**Comment by low-sky** [comment]
Resolved in latest build of `develop`
