### ISSUE TITLE
grid lines not behave as expected

### ISSUE THREAD

**Issue by kswang1029** [Astroua/CARTAvis#190]
Please refer to the attached fits image for this issue. The FITS image is generated with CASA, including three gaussians and two point sources. The field of view is 60 degrees (ra) by 40 degrees (dec). The projection is "SIN". It can be downloaded at "https://drive.google.com/open?id=0B0NqfjC8UsbRLTd0VjMwNDFDaWs"

The expected grid lines should look like the screenshot of the CASA-viewer. 
![screen shot 2016-10-18 at 13 57 22](https://cloud.githubusercontent.com/assets/20819712/19466130/8412fb0a-953b-11e6-8c66-07c1e597d80c.png)
However, CARTA (with Susan's lastest branch) does not show the grid lines as expected. 
![screen shot 2016-10-17 at 17 07 20](https://cloud.githubusercontent.com/assets/20819712/19466136/8d6979f4-953b-11e6-82eb-36d078963038.png)
The plot generated with MIRIAD is also attached.
![screen shot 2016-10-18 at 14 04 07](https://cloud.githubusercontent.com/assets/20819712/19466228/13770476-953c-11e6-8fd4-4a6803cd9251.png)

**Comment by slovelan** [comment]
This should now be fixed.
