### ISSUE TITLE
Extra image view being created when changing a view to an image view

### ISSUE THREAD

**Issue by durga2112** [Astroua/CARTAvis#78]
I have added the "scripted client" label to this issue since I'm not really sure how it can be tested without using the scripted client. Here are the steps to reproduce the bug:

- using the scripted client, take note of the number of image views (by default, this should be 1 after launching CARTA)
- change one of the other views to an image view (this can be done via the right-click menu by selecting View -> CasaImageLoader)
- using the scripted client, take note of the new number of image views

The expected new number of image views would be 2, but it is actually 3. Somewhere along the way, an extra image view has been created.

I can include more detailed instructions for handling the scripted commands if anyone needs them.

**Comment by durga2112** [comment]
I decided to do the Python code up as an iPython notebook so the output could be seen as well. Here's where you can view it:

http://nbviewer.ipython.org/gist/durga2112/0b7deeb9f4e9ac73540a

**Comment by slovelan** [comment]
I have run the exact Python steps submitted with this ticket and was not able to reproduce the bug.  The number of image views reported after changing a view was 2, the correct number.

**Comment by durga2112** [comment]
Oh, okay. I just checked out your pull request #79 and it looks like the issue has been fixed there. I'll close this now.
