### ISSUE TITLE
Too many windows being created with the Window -> Add button

### ISSUE THREAD

**Issue by durga2112** [Astroua/CARTAvis#80]
For any window in the application, access the Window menu (either from the right-click menu or the toolbar), then access one of the options under the Add menu (Bottom, Left, Right, or Top) and click it. Instead of one window being added, numerous windows are added. The number of windows being added also increases each time this operation is performed. For example, in one session, the first time I added a window, I got 4 empty windows being created, then 12, then 28, then 60.

Here's a screenshot of the application window after adding an empty window four times (once from each of the main views - image, animator, histogram, and colormap):

![image](https://cloud.githubusercontent.com/assets/4204212/9851810/b7ca641e-5ac8-11e5-836a-41b85ebe18b9.png)

**Comment by astrilet** [comment]
I think with the new PR #79  this is not longer happening, looks like this has been fixed

**Comment by durga2112** [comment]
Oh, that sounds good. I'll try compiling #79 later today and if this behaviour has indeed been fixed, I'll close the issue.

**Comment by durga2112** [comment]
Hmm, I can't get the code from Susan's branch to run. The window comes up briefly, but then it crashes and I see this error in the terminal:

`terminate called after throwing an instance of 'std::invalid_argument'
  what():  StateInterfaceImpl: No such top-level member 'binCountMax'`

**Comment by astrilet** [comment]
do not fetch code directly from her branch, fetch from her pull ID
git fetch origin pull/ID/head:BRANCHNAME

**Comment by astrilet** [comment]
You might want to delete all files form your ~/CARTA/snapshots directory and its subdirectories

**Comment by durga2112** [comment]
Ah, that seems to have worked. And I can confirm that this is no longer a problem.
