### ISSUE TITLE
Images from the CARTAImages repository not loading

### ISSUE THREAD

**Issue by durga2112** [Astroua/CARTAvis#90]
The following images from the CARTAImages repository are currently not loading for me:

- [ ] both images in the TransposeTest directory
- [x] the image in the BigImageTest directory
- [x] M100_alma.fits from the CubesTest directory

**Comment by astrilet** [comment]
I can only see the problem with images form TransposeTest directory, other two images (form BigImageTest directory and M100_alma.fits) are loading fine on Mac, Ubuntu and CentOS.
h_m51_b_s05_drz_sci.fits takes a while to load but it loads fine, M100_alma.fits loads really fast an without any problems. Looks like your local build problem.

**Comment by durga2112** [comment]
Okay, that's good to know. I'll make sure to try these images on my Ubuntu machine as well. If I'm still having problems there, then we'll see what needs to be done.

**Comment by durga2112** [comment]
I'm running code compiled from the same branch on both machines (Ubuntu VM on Macbook and Ubuntu desktop). On the Ubuntu machine I get the same results as you, but on the VM none of the images I initially mentioned are loading. I wonder if it's just a memory problem or something like that. Is there any way to get more detailed information about why an image doesn't load? Here's the output I see in the terminal:

```
In [11]: i[0].loadFile('/home/jeff/CARTA/Images/CARTAImages/CubesTest/M100_alma.fits')
Debug: WcsPlotter plugin is handling hook # 5 
Debug: CasaImageLoader plugin is handling hook # 1 
Debug: CasaImageLoader plugin trying to load image:  "/home/jeff/CARTA/Images/CARTAImages/CubesTest/M100_alma.fits" 
Warning: 	-paged image open failed:  /home/jeff/CARTA/Images/CARTAImages/CubesTest/M100_alma.fits is not a directory 
 (../../../../../../dev/CARTAvis/carta/cpp/plugins/CasaImageLoader/CasaImageLoader.cpp:90, Image::ImageInterface::SharedPtr CasaImageLoader::loadImage(const QString&))
2015-10-19 13:24:10	WARN	MeasIERS::findTab (file /home/jeff/dev/casacore-2.0.1/measures/Measures/MeasIERS.cc, line 365)	Requested data table Observatories cannot be found in the searched directories:
2015-10-19 13:24:10	WARN	MeasIERS::findTab (file /home/jeff/dev/casacore-2.0.1/measures/Measures/MeasIERS.cc, line 365)+	./
2015-10-19 13:24:10	WARN	MeasIERS::findTab (file /home/jeff/dev/casacore-2.0.1/measures/Measures/MeasIERS.cc, line 365)+	./data/
2015-10-19 13:24:10	WARN	MeasIERS::findTab (file /home/jeff/dev/casacore-2.0.1/measures/Measures/MeasIERS.cc, line 365)+	/home/jeff/aips++/data//ephemerides/
2015-10-19 13:24:10	WARN	MeasIERS::findTab (file /home/jeff/dev/casacore-2.0.1/measures/Measures/MeasIERS.cc, line 365)+	/home/jeff/data//ephemerides/
2015-10-19 13:24:10	WARN	MeasIERS::findTab (file /home/jeff/dev/casacore-2.0.1/measures/Measures/MeasIERS.cc, line 365)+	/usr/local/ephemerides/
2015-10-19 13:24:10	WARN	MeasIERS::findTab (file /home/jeff/dev/casacore-2.0.1/measures/Measures/MeasIERS.cc, line 365)+	/usr/local/ephemerides/
2015-10-19 13:24:10	WARN	MeasIERS::findTab (file /home/jeff/dev/casacore-2.0.1/measures/Measures/MeasIERS.cc, line 365)+	/home/jeff/aips++/data//geodetic/
2015-10-19 13:24:10	WARN	MeasIERS::findTab (file /home/jeff/dev/casacore-2.0.1/measures/Measures/MeasIERS.cc, line 365)+	/home/jeff/data//geodetic/
2015-10-19 13:24:10	WARN	MeasIERS::findTab (file /home/jeff/dev/casacore-2.0.1/measures/Measures/MeasIERS.cc, line 365)+	/usr/local/geodetic/
2015-10-19 13:24:10	WARN	MeasIERS::findTab (file /home/jeff/dev/casacore-2.0.1/measures/Measures/MeasIERS.cc, line 365)+	/usr/local/geodetic/
2015-10-19 13:24:10	SEVERE	MeasTable::initObservatories() (file /home/jeff/dev/casacore-2.0.1/measures/Measures/MeasTable.cc, line 2910)	Cannot read table of Observatories
Warning: 	-unpaged image open failed:  2015-10-19 13:24:10	SEVERE	MeasTable::initObservatories() (file /home/jeff/dev/casacore-2.0.1/measures/Measures/MeasTable.cc, line 2910)	Cannot read table of Observatories 
 (../../../../../../dev/CARTAvis/carta/cpp/plugins/CasaImageLoader/CasaImageLoader.cpp:98, Image::ImageInterface::SharedPtr CasaImageLoader::loadImage(const QString&))
Debug: 	-out of ideas, bailing out 
Warning: Could not find any plugin to load image
 (../../../../../dev/CARTAvis/carta/cpp/core/Data/Image/DataSource.cpp:591, bool Carta::Data::DataSource::_setFileName(const QString&))
Warning: "Unable to load image: /home/jeff/CARTA/Images/CARTAImages/CubesTest/M100_alma.fits.  Please check the file is a supported image format." 
 (../../../../../dev/CARTAvis/carta/cpp/core/Data/Error/ErrorManager.cpp:81, void Carta::Data::ErrorManager::registerWarning(const QString&))
Debug: computeClips std::vector<i x 2>=(10,10) 
Debug: quantile quality check: 
Debug:    0.025 -> 2.5 0.03 0.005  
Debug:    0.975 -> 97.5 0.98 0.005  
Debug: ----------------------------- 
Debug: Trying simple fits parser on "/home/jeff/CARTA/Images/mexinputtest.fits" 
Debug: SimpleFitsParser::loadFile(  "/home/jeff/CARTA/Images/mexinputtest.fits" )
 
Debug: File  "/home/jeff/CARTA/Images/mexinputtest.fits"  open.
 
Warning: "Cannot deal with files that have NAXIS = 0" 
 (../../../../../../dev/CARTAvis/carta/cpp/plugins/WcsPlotter/SimpleFitsParser.cpp:593, bool WcsPlotterPluginNS::SimpleFitsParser::loadFile(const FitsFileLocation&))
Debug: simple fits parser failed 
Debug: Writing 2880 ---- 
Debug: "SIMPLE  =                    T /Standard FITS                                   BITPIX  =                  -32 /Floating point (32 bit)                         NAXIS   =                    2                                                  NAXIS1  =                   10                                                  NAXIS2  =                   10                                                  BSCALE  =   1.000000000000E+00 /PHYSICAL = PIXEL*BSCALE + BZERO                 BZERO   =   0.000000000000E+00                                                  BTYPE   = 'Intensity'                                                           OBJECT  = '        '                                                                                                                                            BUNIT   = '        '           /Brightness (pixel) unit                         EQUINOX =   2.000000000000E+03                                                  RADESYS = 'FK5     '                                                            LONPOLE =   1.800000000000E+02                                                  LATPOLE =  -2.770900000000E+01                                                  PC01_01 =   1.000000000000E+00                                                  PC02_01 =   0.000000000000E+00                                                  PC01_02 =   0.000000000000E+00                                                  PC02_02 =   1.000000000000E+00                                                  CTYPE1  = 'RA---TAN'                                                            CRVAL1  =   5.307100000000E+01                                                  CDELT1  =   1.000000000000E-03                                                  CRPIX1  =   5.000000000000E+00                                                  CUNIT1  = 'deg     '                                                            CTYPE2  = 'DEC--TAN'                                                            CRVAL2  =  -2.770900000000E+01                                                  CDELT2  =   1.000000000000E-03                                                  CRPIX2  =   5.000000000000E+00                                                  CUNIT2  = 'deg     '                                                            EXTNAME = 'SCI     '                                                            EXTVER  =                    1                                                  DATE    = '2015-10-19T13:24:09.702000' /Date FITS file was written              TIMESYS = 'UTC     '           /Time system for HDU                             END                                                                                                                                                                                                                                             " 
Debug: casafits: ("SIMPLE  =                    T /Standard FITS                                   ", "BITPIX  =                  -32 /Floating point (32 bit)                         ", "NAXIS   =                    2                                                  ", "NAXIS1  =                   10                                                  ", "NAXIS2  =                   10                                                  ", "BSCALE  =   1.000000000000E+00 /PHYSICAL = PIXEL*BSCALE + BZERO                 ", "BZERO   =   0.000000000000E+00                                                  ", "BTYPE   = 'Intensity'                                                           ", "OBJECT  = '        '                                                            ", "                                                                                ", "BUNIT   = '        '           /Brightness (pixel) unit                         ", "EQUINOX =   2.000000000000E+03                                                  ", "RADESYS = 'FK5     '                                                            ", "LONPOLE =   1.800000000000E+02                                                  ", "LATPOLE =  -2.770900000000E+01                                                  ", "PC01_01 =   1.000000000000E+00                                                  ", "PC02_01 =   0.000000000000E+00                                                  ", "PC01_02 =   0.000000000000E+00                                                  ", "PC02_02 =   1.000000000000E+00                                                  ", "CTYPE1  = 'RA---TAN'                                                            ", "CRVAL1  =   5.307100000000E+01                                                  ", "CDELT1  =   1.000000000000E-03                                                  ", "CRPIX1  =   5.000000000000E+00                                                  ", "CUNIT1  = 'deg     '                                                            ", "CTYPE2  = 'DEC--TAN'                                                            ", "CRVAL2  =  -2.770900000000E+01                                                  ", "CDELT2  =   1.000000000000E-03                                                  ", "CRPIX2  =   5.000000000000E+00                                                  ", "CUNIT2  = 'deg     '                                                            ", "EXTNAME = 'SCI     '                                                            ", "EXTVER  =                    1                                                  ", "DATE    = '2015-10-19T13:24:09.702000' /Date FITS file was written              ", "TIMESYS = 'UTC     '           /Time system for HDU                             ", "END                                                                             ") 
Debug: Image render 4 xyz 
Debug: frame cache hit 
Out[11]: 
[u'error',
 u'Could not load file /home/jeff/CARTA/Images/CARTAImages/CubesTest/M100_alma.fits']
```

But the only thing that shows up in the GUI is `Warning: "Unable to load image: /home/jeff/CARTA/Images/CARTAImages/CubesTest/M100_alma.fits.  Please check the file is a supported image format." `

**Comment by astrilet** [comment]
you did not load CASA data in your VM machine instance, error message is
right there, it even tells you directory casa library is looking for casa
data files.
I usually put casa data into my /usr/local/ directory or in my ~/data
directory.
Let me know if you need help loading casa data files.
Alex


On Mon, Oct 19, 2015 at 7:48 AM, Jeff Taylor <notifications@github.com>
wrote:

> I'm running code compiled from the same branch on both machines (Ubuntu VM
> on Macbook and Ubuntu desktop). On the Ubuntu machine I get the same
> results as you, but on the VM none of the images I initially mentioned are
> loading. I wonder if it's just a memory problem or something like that. Is
> there any way to get more detailed information about why an image doesn't
> load? Here's the output I see in the terminal:
>
> In [11]: i[0].loadFile('/home/jeff/CARTA/Images/CARTAImages/CubesTest/M100_alma.fits')
> Debug: WcsPlotter plugin is handling hook # 5
> Debug: CasaImageLoader plugin is handling hook # 1
> Debug: CasaImageLoader plugin trying to load image:  "/home/jeff/CARTA/Images/CARTAImages/CubesTest/M100_alma.fits"
> Warning:    -paged image open failed:  /home/jeff/CARTA/Images/CARTAImages/CubesTest/M100_alma.fits is not a directory
>  (../../../../../../dev/CARTAvis/carta/cpp/plugins/CasaImageLoader/CasaImageLoader.cpp:90, Image::ImageInterface::SharedPtr CasaImageLoader::loadImage(const QString&))
> 2015-10-19 13:24:10 WARN    MeasIERS::findTab (file /home/jeff/dev/casacore-2.0.1/measures/Measures/MeasIERS.cc, line 365)  Requested data table Observatories cannot be found in the searched directories:
> 2015-10-19 13:24:10 WARN    MeasIERS::findTab (file /home/jeff/dev/casacore-2.0.1/measures/Measures/MeasIERS.cc, line 365)+ ./
> 2015-10-19 13:24:10 WARN    MeasIERS::findTab (file /home/jeff/dev/casacore-2.0.1/measures/Measures/MeasIERS.cc, line 365)+ ./data/
> 2015-10-19 13:24:10 WARN    MeasIERS::findTab (file /home/jeff/dev/casacore-2.0.1/measures/Measures/MeasIERS.cc, line 365)+ /home/jeff/aips++/data//ephemerides/
> 2015-10-19 13:24:10 WARN    MeasIERS::findTab (file /home/jeff/dev/casacore-2.0.1/measures/Measures/MeasIERS.cc, line 365)+ /home/jeff/data//ephemerides/
> 2015-10-19 13:24:10 WARN    MeasIERS::findTab (file /home/jeff/dev/casacore-2.0.1/measures/Measures/MeasIERS.cc, line 365)+ /usr/local/ephemerides/
> 2015-10-19 13:24:10 WARN    MeasIERS::findTab (file /home/jeff/dev/casacore-2.0.1/measures/Measures/MeasIERS.cc, line 365)+ /usr/local/ephemerides/
> 2015-10-19 13:24:10 WARN    MeasIERS::findTab (file /home/jeff/dev/casacore-2.0.1/measures/Measures/MeasIERS.cc, line 365)+ /home/jeff/aips++/data//geodetic/
> 2015-10-19 13:24:10 WARN    MeasIERS::findTab (file /home/jeff/dev/casacore-2.0.1/measures/Measures/MeasIERS.cc, line 365)+ /home/jeff/data//geodetic/
> 2015-10-19 13:24:10 WARN    MeasIERS::findTab (file /home/jeff/dev/casacore-2.0.1/measures/Measures/MeasIERS.cc, line 365)+ /usr/local/geodetic/
> 2015-10-19 13:24:10 WARN    MeasIERS::findTab (file /home/jeff/dev/casacore-2.0.1/measures/Measures/MeasIERS.cc, line 365)+ /usr/local/geodetic/
> 2015-10-19 13:24:10 SEVERE  MeasTable::initObservatories() (file /home/jeff/dev/casacore-2.0.1/measures/Measures/MeasTable.cc, line 2910)   Cannot read table of Observatories
> Warning:    -unpaged image open failed:  2015-10-19 13:24:10    SEVERE  MeasTable::initObservatories() (file /home/jeff/dev/casacore-2.0.1/measures/Measures/MeasTable.cc, line 2910)   Cannot read table of Observatories
>  (../../../../../../dev/CARTAvis/carta/cpp/plugins/CasaImageLoader/CasaImageLoader.cpp:98, Image::ImageInterface::SharedPtr CasaImageLoader::loadImage(const QString&))
> Debug:  -out of ideas, bailing out
> Warning: Could not find any plugin to load image
>  (../../../../../dev/CARTAvis/carta/cpp/core/Data/Image/DataSource.cpp:591, bool Carta::Data::DataSource::_setFileName(const QString&))
> Warning: "Unable to load image: /home/jeff/CARTA/Images/CARTAImages/CubesTest/M100_alma.fits.  Please check the file is a supported image format."
>  (../../../../../dev/CARTAvis/carta/cpp/core/Data/Error/ErrorManager.cpp:81, void Carta::Data::ErrorManager::registerWarning(const QString&))
> Debug: computeClips std::vector<i x 2>=(10,10)
> Debug: quantile quality check:
> Debug:    0.025 -> 2.5 0.03 0.005
> Debug:    0.975 -> 97.5 0.98 0.005
> Debug: -----------------------------
> Debug: Trying simple fits parser on "/home/jeff/CARTA/Images/mexinputtest.fits"
> Debug: SimpleFitsParser::loadFile(  "/home/jeff/CARTA/Images/mexinputtest.fits" )
>
> Debug: File  "/home/jeff/CARTA/Images/mexinputtest.fits"  open.
>
> Warning: "Cannot deal with files that have NAXIS = 0"
>  (../../../../../../dev/CARTAvis/carta/cpp/plugins/WcsPlotter/SimpleFitsParser.cpp:593, bool WcsPlotterPluginNS::SimpleFitsParser::loadFile(const FitsFileLocation&))
> Debug: simple fits parser failed
> Debug: Writing 2880 ----
> Debug: "SIMPLE  =                    T /Standard FITS                                   BITPIX  =                  -32 /Floating point (32 bit)                         NAXIS   =                    2                                                  NAXIS1  =                   10                                                  NAXIS2  =                   10                                                  BSCALE  =   1.000000000000E+00 /PHYSICAL = PIXEL*BSCALE + BZERO                 BZERO   =   0.000000000000E+00                                                  BTYPE   = 'Intensity'                                                           OBJECT  = '        '                                                                                                                                            BUNIT   = '        '           /Brightness (pixel) unit                         EQUINOX =   2.000000000000E+03                                                  RADESYS = 'FK5     '
>                                                    LONPOLE =   1.800000000000E+02                                                  LATPOLE =  -2.770900000000E+01                                                  PC01_01 =   1.000000000000E+00                                                  PC02_01 =   0.000000000000E+00                                                  PC01_02 =   0.000000000000E+00                                                  PC02_02 =   1.000000000000E+00                                                  CTYPE1  = 'RA---TAN'                                                            CRVAL1  =   5.307100000000E+01                                                  CDELT1  =   1.000000000000E-03                                                  CRPIX1  =   5.000000000000E+00                                                  CUNIT1  = 'deg     '                                                            CTYPE2  = 'DEC--TAN'
>               CRVAL2  =  -2.770900000000E+01                                                  CDELT2  =   1.000000000000E-03                                                  CRPIX2  =   5.000000000000E+00                                                  CUNIT2  = 'deg     '                                                            EXTNAME = 'SCI     '                                                            EXTVER  =                    1                                                  DATE    = '2015-10-19T13:24:09.702000' /Date FITS file was written              TIMESYS = 'UTC     '           /Time system for HDU                             END                                                                                                                                                                                                                                             "
> Debug: casafits: ("SIMPLE  =                    T /Standard FITS                                   ", "BITPIX  =                  -32 /Floating point (32 bit)                         ", "NAXIS   =                    2                                                  ", "NAXIS1  =                   10                                                  ", "NAXIS2  =                   10                                                  ", "BSCALE  =   1.000000000000E+00 /PHYSICAL = PIXEL*BSCALE + BZERO                 ", "BZERO   =   0.000000000000E+00                                                  ", "BTYPE   = 'Intensity'                                                           ", "OBJECT  = '        '                                                            ", "                                                                                ", "BUNIT   = '        '           /Brightness (pixel) unit                         ", "EQUINOX =   2.000000000000E+03
>                           ", "RADESYS = 'FK5     '                                                            ", "LONPOLE =   1.800000000000E+02                                                  ", "LATPOLE =  -2.770900000000E+01                                                  ", "PC01_01 =   1.000000000000E+00                                                  ", "PC02_01 =   0.000000000000E+00                                                  ", "PC01_02 =   0.000000000000E+00                                                  ", "PC02_02 =   1.000000000000E+00                                                  ", "CTYPE1  = 'RA---TAN'                                                            ", "CRVAL1  =   5.307100000000E+01                                                  ", "CDELT1  =   1.000000000000E-03                                                  ", "CRPIX1  =   5.000000000000E+00                                                  ", "CUNIT1  = 'deg     '
>                                      ", "CTYPE2  = 'DEC--TAN'                                                            ", "CRVAL2  =  -2.770900000000E+01                                                  ", "CDELT2  =   1.000000000000E-03                                                  ", "CRPIX2  =   5.000000000000E+00                                                  ", "CUNIT2  = 'deg     '                                                            ", "EXTNAME = 'SCI     '                                                            ", "EXTVER  =                    1                                                  ", "DATE    = '2015-10-19T13:24:09.702000' /Date FITS file was written              ", "TIMESYS = 'UTC     '           /Time system for HDU                             ", "END                                                                             ")
> Debug: Image render 4 xyz
> Debug: frame cache hit
> Out[11]:
> [u'error',
>  u'Could not load file /home/jeff/CARTA/Images/CARTAImages/CubesTest/M100_alma.fits']
>
> But the only thing that shows up in the GUI is Warning: "Unable to load
> image: /home/jeff/CARTA/Images/CARTAImages/CubesTest/M100_alma.fits. Please
> check the file is a supported image format."
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Astroua/CARTAvis/issues/90#issuecomment-149218338>.
>

**Comment by durga2112** [comment]
Ah, thanks! Now the images are loading on my VM as well. So now the only problematic images are the TransposeTest images.

**Comment by astrilet** [comment]
They are fixed with latest PR from Susan

**Comment by astrilet** [comment]
PR #88 resolved this issue
