### ISSUE TITLE
snapshots directory structure not being created

### ISSUE THREAD

**Issue by low-sky** [Astroua/CARTAvis#91]
This occurs on the Mac version at least.  The CARTA/snapshots directory should contain directories called "data", "layout", and "preferences" for save/restore functionality to work.  Does the install script need to be adapted to create these if they don't exist?

@astrilet

**Comment by astrilet** [comment]
This is indeed an issue I will fix the script

**Comment by pfederl** [comment]
I don't see a need for a script to do that. This can be easily accomplished
directly in c++. In my opinion if we can we should avoid having any
installation scripts. Just untar and run. ..

**Comment by astrilet** [comment]
This problem should be resolved now
